-- Create 25+ categories for AuraCart dropshipping platform
INSERT INTO public.categories (name, slug, description, display_order, is_active) VALUES
('Electronics', 'electronics', 'Smartphones, tablets, laptops and accessories', 1, true),
('Fashion', 'fashion', 'Clothing, shoes and accessories for all', 2, true),
('Home & Garden', 'home-garden', 'Furniture, décor, and outdoor essentials', 3, true),
('Beauty & Health', 'beauty-health', 'Skincare, makeup, and wellness products', 4, true),
('Sports & Outdoors', 'sports-outdoors', 'Fitness gear, camping, and sports equipment', 5, true),
('Jewelry & Watches', 'jewelry-watches', 'Rings, necklaces, bracelets and timepieces', 6, true),
('Toys & Games', 'toys-games', 'Kids toys, board games, and puzzles', 7, true),
('Automotive', 'automotive', 'Car accessories, parts, and tools', 8, true),
('Pet Supplies', 'pet-supplies', 'Food, toys, and accessories for pets', 9, true),
('Baby & Kids', 'baby-kids', 'Baby gear, clothing, and nursery items', 10, true),
('Office Supplies', 'office-supplies', 'Stationery, desk organizers, and tech', 11, true),
('Kitchen & Dining', 'kitchen-dining', 'Cookware, appliances, and tableware', 12, true),
('Bags & Luggage', 'bags-luggage', 'Backpacks, handbags, and travel cases', 13, true),
('Phones & Accessories', 'phones-accessories', 'Cases, chargers, and phone gadgets', 14, true),
('Computer & Networking', 'computer-networking', 'Laptops, desktops, and networking gear', 15, true),
('Audio & Video', 'audio-video', 'Headphones, speakers, and cameras', 16, true),
('Gaming', 'gaming', 'Consoles, controllers, and gaming accessories', 17, true),
('Smart Home', 'smart-home', 'Smart devices, security, and automation', 18, true),
('Tools & Hardware', 'tools-hardware', 'Power tools, hand tools, and equipment', 19, true),
('Lighting', 'lighting', 'LED lights, lamps, and fixtures', 20, true),
('Wigs & Hair', 'wigs-hair', 'Wigs, extensions, and hair accessories', 21, true),
('Art & Craft', 'art-craft', 'Art supplies, DIY kits, and craft materials', 22, true),
('Musical Instruments', 'musical-instruments', 'Guitars, keyboards, and accessories', 23, true),
('Security & Surveillance', 'security-surveillance', 'Cameras, alarms, and monitoring systems', 24, true),
('Outdoor Recreation', 'outdoor-recreation', 'Camping, hiking, and adventure gear', 25, true),
('Men''s Fashion', 'mens-fashion', 'Clothing, shoes and accessories for men', 26, true),
('Women''s Fashion', 'womens-fashion', 'Clothing, shoes and accessories for women', 27, true),
('Accessories', 'accessories', 'Belts, hats, sunglasses and more', 28, true);